openMF/android-client

mifosng-android/mifosng-android.iml
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientDetailsFragment.java
mifosng-android/src/main/res/layout/fragment_client_details.xml

added progress bar for client image upload progress

---

mifosng-android/src/main/res/values-ca/strings.xml

This was done as part of:
https://www.google-melange.com/gci/task/view/google/gci2014/5828280368234496

Translate strings to Catalan

---

mifosng-android/src/main/res/values-es/strings.xml

This was done as part of:
https://www.google-melange.com/gci/task/view/google/gci2014/5896044751618048

Translate strings to Spanish

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/LoginActivity.java
mifosng-android/src/main/res/layout/activity_login.xml

Worked on the following: <br />
(1) Users experienced an error that produced an SSLHandshakeException<br /> 
(2) If user inputs a number into the port number field that exceeds the allowable size of an int data type, the application fails and exits due to NumberFormationException<br />
(3) If user inputs a character into the port number input field after a number, the application fails and exits due to NumberFormatException<br />
(4) If user inputs a character into the port number input field as the first key input, the application fails and exits due to NullPointerException<br />
(5) If user enters an incorrect port number, then chooses to not enter any port number, the application will be unable to login until the application is restarted

Changes to LoginActivity class

---

mifosng-android/src/main/AndroidManifest.xml
mifosng-android/src/main/java/com/mifos/mifosxdroid/OfflineCenterInputActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientSearchFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CreateNewClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardFragmentActivity.java

Link to issue:  https://mifosforge.jira.com/browse/MIFOSAC-87
Do we need to add back button functionality in Client Detail and internal pages as well? If yes, to home or to parent page?

fixed #MIFOSAC-87 back button linked to home screen

---

.travis.yml
mifosng-android/build.gradle
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientSearchFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CreateNewClientFragment.java

- Added com.android.support:design:23.0.1 - support library (for material design)<br/>
[Google Material Design support library] (http://developer.android.com/tools/support-library/features.html#design) <br/>
- Design library doesn't compiles with old google-play-services library, so, only the way to use it - update google-play-services. I've used com.google.android.gms:play-services-location:8.3.0 - it ships as separate package, and this way the size of APK will be much more lower. I've updated receiving location as it described in official documentation. <br/> [Google Play Services - receiving location updates](http://developer.android.com/training/location/retrieve-current.html)<br/>
It works correctly, and without this changes it's not possible to work with official way to implement …

Material design library

---

.travis.yml
mifosng-android/build.gradle
mifosng-android/src/main/java/com/mifos/mifosxdroid/LoginActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientSearchFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CreateNewClientFragment.java
mifosng-android/src/main/res/layout/activity_login.xml
mifosng-android/src/main/res/values/styles_button.xml
mifosng-android/src/main/res/values/styles_edit.xml
mifosng-android/src/main/res/values/styles_frame.xml
mifosng-android/src/main/res/values/styles_linear.xml
mifosng-android/src/main/res/values/styles_relative.xml
mifosng-android/src/main/res/values/styles_scroll.xml
mifosng-android/src/main/res/values/styles_text.xml
mifosng-android/src/main/res/values/styles_text_input.xml
mifosng-android/src/main/res/values/styles_toolbar.xml

- I haven't touched code mostly, just layout changes
- I've moved mostly used element attributes to styles*.xml files. for instance, login_acvity.xml is now 100 lines of code instead of 200, and it's much more easy to read through<br>
[Google Styles Guidelines](http://developer.android.com/guide/topics/ui/themes.html)
For example 
```
<TextView
android:layout_width="fill_parent"
android:layout_height="wrap_content"
android:textColor="#00FF00"
android:typeface="monospace"
android:text="@string/hello" />
```
will be easily turned to this: 
```
<TextView
style="@style/CodeFont"
android:text="@string/hello" />
```

Material design - LoginActivity

---

mifosng-android/build.gradle
mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/LoanTransactionAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/SavingsAccountTransactionsListAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CreateNewCenterFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CreateNewClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CreateNewGroupFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardFragmentActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/GenerateCollectionSheetFragment.java
mifosng-android/src/main/java/com/mifos/objects/organisation/ClientClassificationOptions.java
mifosng-android/src/main/java/com/mifos/objects/organisation/ClientTypeOptions.java
mifosng-android/src/main/java/com/mifos/objects/organisation/GenderOptions.java
mifosng-android/src/main/java/com/mifos/services/API.java
mifosng-android/src/main/java/com/mifos/services/data/CenterPayload.java
mifosng-android/src/main/java/com/mifos/services/data/ClientPayload.java
mifosng-android/src/main/java/com/mifos/services/data/GroupPayload.java
mifosng-android/src/main/java/com/mifos/utils/DateHelper.java
mifosng-android/src/main/java/com/mifos/utils/FragmentConstants.java
mifosng-android/src/main/res/layout/fragment_create_new_center.xml
mifosng-android/src/main/res/layout/fragment_create_new_client.xml
mifosng-android/src/main/res/layout/fragment_create_new_group.xml
mifosng-android/src/main/res/layout/fragment_loan_account_summary.xml
mifosng-android/src/main/res/menu/client_search.xml
mifosng-android/src/main/res/values-ca/strings.xml
mifosng-android/src/main/res/values-en/strings.xml
mifosng-android/src/main/res/values-es/strings.xml
mifosng-android/src/main/res/values/strings.xml
mifosng-android/src/main/res/values/styles_text.xml

@ishan1604  hope this resolves the squash issue , though it seems i squashed so many commits, :-(
Can you kindly advice me on the best way to resolve this issue.

fixing squashing issue- added the ability to create center, group and client

---

mifosng-android/src/main/res/values/styles.xml

Signed-off-by: Prempal Singh <prempal.42@gmail.com>

fix primary dark color

---

mifosng-android/build.gradle
mifosng-android/src/main/AndroidManifest.xml
mifosng-android/src/main/java/com/mifos/api/model/GpsCoordinatesRequest.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/LocationService.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/activity/MifosMapActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/activity/PathTrackingActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/activity/PinpointClientActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardFragmentActivity.java
mifosng-android/src/main/res/layout/activity_path_tracker.xml
mifosng-android/src/main/res/menu/client.xml
mifosng-android/src/main/res/menu/client_save_pin.xml
mifosng-android/src/main/res/menu/client_search.xml
mifosng-android/src/main/res/values/colors.xml
mifosng-android/src/main/res/values/strings.xml

Hi! :) 
This PR contains integration with Google Maps and location features:
**- Pinpointing client location**
**MifosMapActivity** - activity that holding SupportMapFragment (to make it work on API level < 16). 
**PinpointClientActivity** - responsible for onClick callbacks, pinpointing, and saving client location. 
To store field officer path I've created **LocationService**. It designed to work with location in 'Optmial Power Mode'. To request saving path we should connect to it through ServiceConnection, and to call appropriate method. 
During recording I'm showing now a notification with recording status. 
Data is stored as list of LatLng coordinates, and before sending it to backend it will be converted to PolyLine - https://developers.google.com/maps/documentation/utilities/polyline …

GIS Integration

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/LoginActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientListFragment.java

On Login Page If network connection is not available then snackbar would show message about network connection.

MIFOAC-117 Showing the Connection Status resolved

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/SurveyLastFragment.java

Creating empty ScorecardValues list in case no questions were answered.
Fixes [MIFOAC-109](https://mifosforge.jira.com/projects/MIFOSAC/issues/MIFOSAC-109)
Signed-off-by: Suhaib Khan <suheb.work@gmail.com>

Fixes MIFOSAC-109

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/DocumentListAdapter.java
mifosng-android/src/main/res/layout/row_document_list.xml

Signed-off-by: Prempal Singh <prempal.42@gmail.com>

fix crash in DocumentListAdapter

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CreateNewCenterFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CreateNewClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CreateNewGroupFragment.java

@ishan1604 In this I have added only missing validations and removed few unnecessary such as compulsory middle name as many people don't have middle name as discussed with @nellyk .Beside that I have fixed basic typos.

MIFOSAC-113 Missing validations added

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/ClientChooseAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/ClientSearchAdapter.java

Crash fix in Client list in search and survey list due to null client value.

Null client name and object check.

---

mifosng-android/src/main/java/com/mifos/api/ApiManager.java
mifosng-android/src/main/java/com/mifos/api/services/ClientService.java
mifosng-android/src/main/java/com/mifos/api/services/CreateSavingsAccountService.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CreateNewClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/SavingsAccountFragment.java
mifosng-android/src/main/java/com/mifos/objects/InterestType.java
mifosng-android/src/main/java/com/mifos/objects/db/Account.java
mifosng-android/src/main/java/com/mifos/objects/db/Currency.java
mifosng-android/src/main/java/com/mifos/objects/db/MifosGroup.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/ClientsTemplate.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/OfficeOptions.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/Options.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/SavingProductOptions.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/StaffOptions.java
mifosng-android/src/main/java/com/mifos/objects/templates/savings/AccountOptions.java
mifosng-android/src/main/java/com/mifos/objects/templates/savings/SavingProductsTemplate.java
mifosng-android/src/main/java/com/mifos/objects/templates/savings/SavingsAccountTransactionTemplate.java

PR #219 squashed . @ishan1604  Please review and merge.

Multiple API calls -> Single call. Client and Savings templates' model added.

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/activity/PathTrackingActivity.java

Minor fix. Missing back button added to Track my path screen.
@ishan1604 review it!
@fomenkoo removed extra line space.

fix MIFOSAC-121 back button added in track my path screen

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/ClientListFragment.java

There was not Refresh functionality properly enable and LoadMore was not properly working.
Now it is fixed and officers can Refresh the Client List and view the Next Pagination Client List using scrolling down the list. 
@fomenkoo Please Review 
Thanks.

Loadmore ClientList and Refresh the ClientList fix.

---

mifosng-android/src/instrumentTest/java/com/mifos/mifosxdroid/tests/CreateNewClientFragmentTest.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CreateNewClientFragment.java

fixes MOFISAC-124
when creating a new client and changing the submission date, the birth date doesn't change
And added an activity test for it.

submission and birthdate became independent

---

mifosng-android/src/main/res/layout/row_group_list.xml

fixes MIFOSAC-132
(http://i.imgur.com/TfmlgVG.png)

group list's UI enhacment

---

mifosng-android/src/main/res/layout/fragment_groups.xml
mifosng-android/src/main/res/layout/row_group_name.xml
mifosng-android/src/main/res/values/colors.xml

MIFOSAC-132 now the group names list follow the material design two-line list specs
(http://i.imgur.com/FuJQWdr.png)

enhance group names list's look

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/uihelpers/MFDatePicker.java

Earlier on client creation user was able to select future dates in date of birth, via this fix it will not be possible to select the future dates.

Fixed Mifosac-125 future date picking issue resolved

---

mifosng-android/src/instrumentTest/java/com/mifos/mifosxdroid/tests/ClientChargesTest.java

MIFOSAC-65
an activity test for the client's charges(open charges and create new
charge)

Client Charges Activity test

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/LoginActivity.java

Sorry for the last PR inconvenience.

#Fixed MIFOSAC -122 / Re-login fix after using wrong tenant ID.

---

mifosng-android/src/instrumentTest/java/com/mifos/mifosxdroid/tests/SurveyActivityTest.java
mifosng-android/src/instrumentTest/java/com/mifos/mifosxdroid/tests/SurveyQuestionViewPagerActivityTest.java

MIFOSAC-65
a set of activity tests for opening and answering a survey

Survey activity tests

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/ClientNameListAdapter.java
mifosng-android/src/main/res/layout/row_client_name.xml

MIFOSAC-145
- lazy loads the profile picture
- uses a circle image view
- removes that clickable drawable when clicking the porfile picture
- fixes the margins and paddings as per the material design guidelines
(http://i.imgur.com/F4ppjcB.png)

enhance clients list

---

mifosng-android/src/instrumentTest/java/com/mifos/mifosxdroid/tests/CreateNewCenterFragmentTest.java

MIFOSAC-65
activity test for CreateNewCenterFragment

activity test for create new center

---

mifosng-android/build.gradle
mifosng-android/src/main/java/com/mifos/utils/DateHelper.java
mifosng-android/src/test/java/com/mifos/mifosxdroid/tests/DateHelpersTest.java

MIFOSAC-65
- added unit tests for the methods used
- added documentation

unit tests for DateHelper

---

mifosng-android/src/instrumentTest/java/com/mifos/mifosxdroid/tests/CreateNewGroupFragmentTest.java

MIFOSAC-65
activity test for CreateNewGroupFragment

create new group test

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/SavingsAccountTransactionFragment.java

This fixes "Recurring Accounts withdrawal or payment crashes application"
(https://github.com/openMF/android-client/issues/147) as well.
A user will be able to make a withdrawal or make a deposit. The code
will replace all string or character values with empty values so that
the integer (int) value can be processed.

MIFOSAC-140: Fixing crashes for Recurring Accounts Transactions

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/LoanTransactionAdapter.java

NPE LoanTransaction Fix

---

mifosng-android/src/main/java/com/mifos/api/DataManager.java
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerClient.java
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerLoan.java
mifosng-android/src/main/java/com/mifos/api/local/databasehelper/DatabaseHelperClient.java
mifosng-android/src/main/java/com/mifos/api/local/databasehelper/DatabaseHelperLoan.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountsummary/LoanAccountSummaryPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanrepayment/LoanRepaymentFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanrepayment/LoanRepaymentPresenter.java
mifosng-android/src/main/java/com/mifos/objects/PaymentTypeOption.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/ActualDisbursementDate.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/AmortizationType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/InterestCalculationPeriodType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/InterestRateFrequencyType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/InterestType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/LoanRepaymentRequest.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/LoanWithAssociations.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/RepaymentFrequencyType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/RepaymentSchedule.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/Status.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/Summary.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/TermPeriodFrequencyType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/Timeline.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/Options.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/LoanRepaymentTemplate.java

Offline loan transaction Saving to Database

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Add Guidelines for opening Issue and making Pull Request.

Issue and Pull request Template 

---

mifosng-android/src/main/AndroidManifest.xml
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerSavings.java
mifosng-android/src/main/java/com/mifos/api/local/databasehelper/DatabaseHelperLoan.java
mifosng-android/src/main/java/com/mifos/api/local/databasehelper/DatabaseHelperSavings.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/SyncLoanRepaymentAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/SyncSavingsAccountTransactionAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncclientsdialog/SyncClientsDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncclientsdialog/SyncClientsDialogMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncclientsdialog/SyncClientsDialogPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ActivityComponent.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/offlinedashbarod/OfflineDashboardFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/offlinedashbarod/OfflineDashboardMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/offlinedashbarod/OfflineDashboardPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncsavingsaccounttransaction/SyncSavingsAccountTransactionActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncsavingsaccounttransaction/SyncSavingsAccountTransactionFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncsavingsaccounttransaction/SyncSavingsAccountTransactionMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncsavingsaccounttransaction/SyncSavingsAccountTransactionPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingaccounttransaction/SavingsAccountTransactionPresenter.java
mifosng-android/src/main/java/com/mifos/objects/accounts/savings/SavingsAccountTransactionRequest.java
mifosng-android/src/main/java/com/mifos/objects/zipmodels/SavingsAccountAndTransactionTemplate.java
mifosng-android/src/main/java/com/mifos/utils/Utils.java
mifosng-android/src/main/res/layout/item_sync_savings_account_transaction.xml
mifosng-android/src/main/res/values/strings.xml

Adapter added and basic saving Account transaction Fragment added with presenter and view
Offline Sync SavingsAccountTransaction Feature added.
Offline Sync  SavingsAccountTransaction  and SavingsAccountsTemplate On Muti-Selection
Documentation added

Offline Sync SavingsAccountTransaction

---

mifosng-android/src/main/java/com/mifos/api/MifosOkHttpClient.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncclientsdialog/SyncClientsDialogPresenter.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/Summary.java

Fix the NumberFormat Exception while syncing LoanById
Exception handled in onError

Bug fix while syncing LoanById

---

mifosng-android/src/commonTest/java/com/mifos/mifosxdroid/FakeRemoteDataSource.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/ClientNameListAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/core/MifosBaseFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListPresenter.java
mifosng-android/src/main/java/com/mifos/objects/group/GroupWithAssociations.java
mifosng-android/src/main/java/com/mifos/utils/Constants.java
mifosng-android/src/main/res/values/strings.xml
mifosng-android/src/test/java/com/mifos/mifosxdroid/online/ClientListPresenterTest.java
mifosng-android/src/test/resources/clients.json

1. Fix Group Clients.
2. Written ClientListFragment in Such manner that it can show external ClientList.
3. ClientListPresenterTest Fix.

Fix Group Clients and ClientListFragmentPresenterTest

---

mifosng-android/src/main/java/com/mifos/api/DataManager.java
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerDocument.java
mifosng-android/src/main/java/com/mifos/api/services/DocumentService.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/documentdialog/DocumentDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/documentdialog/DocumentDialogMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/documentdialog/DocumentDialogPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ApplicationComponent.java
mifosng-android/src/main/java/com/mifos/utils/AndroidVersionUtil.java
mifosng-android/src/main/java/com/mifos/utils/CheckSelfPermissionAndRequest.java
mifosng-android/src/main/java/com/mifos/utils/Constants.java
mifosng-android/src/main/java/com/mifos/utils/FileUtils.java
mifosng-android/src/main/res/layout/dialog_fragment_document.xml
mifosng-android/src/main/res/values/strings.xml

Add CheckPermission READ_EXTERNAL_STORAGE in runtime.
Add getPath of Document on any device.
Fix Upload Document.

Fix Documents Upload

---

build.gradle
mifosng-android/build.gradle
mifosng-android/src/main/java/com/mifos/api/BaseApiManager.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/DocumentListAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/documentdialog/DocumentDialogPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/documentlist/DocumentListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/documentlist/DocumentListMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/documentlist/DocumentListPresenter.java
mifosng-android/src/main/res/values/strings.xml
mifosng-android/src/test/java/com/mifos/mifosxdroid/online/DocumentListPresenterTest.java

Upload any type of document from any device API 10 and above.

Upload Any type of Document

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsPresenter.java

Upload Client Profile Image Fix

Upload Client Image Fix

---

.travis.yml

Gitter channel integration with travis build.

Gitter channel integration with travis build

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/login/LoginActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardActivity.java
mifosng-android/src/main/java/com/mifos/utils/PrefManager.java

**Issue**: https://github.com/openMF/android-client/issues/339
On branch loggedin_user_detail
Changes to be committed:
modified:   mifosng-android/src/main/java/com/mifos/mifosxdroid/login/LoginActivity.java
modified:   mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardActivity.java
modified:   mifosng-android/src/main/java/com/mifos/utils/PrefManager.java

Shows logged in user's detail

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupFragment.java
mifosng-android/src/main/java/com/mifos/utils/ValidationUtil.java

Fix: group name validation during creation of group.

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupFragment.java
mifosng-android/src/main/java/com/mifos/utils/ValidationUtil.java

Reverts openMF/android-client#351

Revert "Fix: group name validation during creation of group."

---

mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerCenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/CentersListAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerlist/CenterListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerlist/CenterListMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerlist/CenterListPresenter.java
mifosng-android/src/main/java/com/mifos/objects/group/Center.java
mifosng-android/src/main/res/layout/fragment_centers_list.xml
mifosng-android/src/main/res/values/strings.xml
mifosng-android/src/test/java/com/mifos/mifosxdroid/online/CenterListPresenterTest.java

CenterList Enhance.

---

.travis.yml
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerGroups.java
mifosng-android/src/main/java/com/mifos/api/local/databasehelper/DatabaseHelperClient.java
mifosng-android/src/main/java/com/mifos/api/local/databasehelper/DatabaseHelperGroups.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncgroupsdialog/SyncGroupsDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncgroupsdialog/SyncGroupsDialogMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncgroupsdialog/SyncGroupsDialogPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/GroupsActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupdetails/GroupDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupdetails/GroupDetailsMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupdetails/GroupDetailsPresenter.java
mifosng-android/src/main/java/com/mifos/objects/client/Client.java
mifosng-android/src/main/res/layout/dialog_fragment_sync_groups.xml
mifosng-android/src/main/res/menu/group.xml
mifosng-android/src/main/res/values/strings.xml

Added : Feature Group Associate Client
Multi-Selection added.
Sync Group Details and Group Associates Client.
Fix : Travis required "sudo" that is fixed now.

Sync Group and Associate Clients on Multi-Selection

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewcenter/CreateNewCenterFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupFragment.java
mifosng-android/src/main/java/com/mifos/utils/ValidationUtil.java

Fix: Group, Center, Client Name Validation during Creation

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveylist/SurveyListFragment.java
mifosng-android/src/main/res/values/strings.xml

MIFOSAC-159 Message for selecting the survey is appearing despite no survey available resolved

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.java

Image downloading through glide instead of async task

---

mifosng-android/src/main/java/com/mifos/api/DataManager.java
mifosng-android/src/main/java/com/mifos/api/services/LoanService.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/grouploanaccount/GroupLoanAccountFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/grouploanaccount/GroupLoanAccountMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/grouploanaccount/GroupLoanAccountPresenter.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/CalendarOptions.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/CalendarOptionsType.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/Charges.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/EntityType.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/Frequency.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/Group.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/GroupLoanTemplate.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/GroupTimeline.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/OverdueCharges.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/RepaymentFrequencyDaysOfWeekTypeOptions.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/RepeatsOnNthDayOfMonth.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/Status.java

gradle
mvpImplemented
build passed
changesReview
correctedDropDown

Drop-down values when creating loan account at group level aren't available #358 Resolved

---

mifosng-android/src/main/java/com/mifos/objects/templates/loans/LoanTemplate.java

NumberFormatException While fetching LoanAccount Template #383 Resolved

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/core/MifosBaseActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/core/MifosBaseFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientsearch/ClientSearchFragment.java

fix: Hide keyboard on opening Navigation Drawer or clicking Search button

---

mifosng-android/src/main/res/values/strings.xml

* Change 'intrest' to 'interest'
Fixes #406

Fix typo in message for the nominal annual interest field

---

mifosng-android/src/main/res/values/strings.xml

* Change 'intrest' to 'interest'

Fix Interest Compounding Period Label

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CentersActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/grouplist/GroupListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccount/SavingsAccountFragment.java
mifosng-android/src/main/java/com/mifos/services/data/SavingsPayload.java
mifosng-android/src/main/java/com/mifos/utils/Constants.java
mifosng-android/src/main/res/menu/menu_center.xml

Add menu item to center view that visible in list of groups only and allow to create center saving account.

Add saving account in center view

---

mifosng-android/src/main/AndroidManifest.xml

Issue #413
Adds RTL support, supports multiple right-to-left languages(like Arabic) 
Note: All layout files have to be changed too

Feat : Adds RTL Support

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerlist/CenterListFragment.java
mifosng-android/src/main/res/values/strings.xml

Fixes of #435 #296
This PR fixes the crash, If there is no meeting schedule for center.

Fix : No meeting Found for center

---

mifosng-android/src/main/java/com/mifos/objects/accounts/loan/AmortizationType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/Currency.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/InterestCalculationPeriodType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/InterestRateFrequencyType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/InterestType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/LoanType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/Loans.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/RepaymentFrequencyType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/Summary.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/TermPeriodFrequencyType.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/Timeline.java

Add API Response Model in LoanAccountFragment #385 Resolved

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CentersActivity.java

fix: Crash on selecting Centers screen from Nav Drawer

---

mifosng-android/src/instrumentTest/java/com/mifos/mifosxdroid/tests/CreateNewCenterFragmentTest.java
mifosng-android/src/instrumentTest/java/com/mifos/mifosxdroid/tests/CreateNewClientFragmentTest.java
mifosng-android/src/instrumentTest/java/com/mifos/mifosxdroid/tests/CreateNewGroupFragmentTest.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewcenter/CreateNewCenterFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccount/SavingsAccountFragment.java
mifosng-android/src/main/java/com/mifos/objects/client/Address.java
mifosng-android/src/main/java/com/mifos/objects/client/ClientPayload.java
mifosng-android/src/main/res/layout/fragment_add_savings_account.xml
mifosng-android/src/main/res/layout/fragment_create_new_center.xml
mifosng-android/src/main/res/layout/fragment_create_new_client.xml
mifosng-android/src/main/res/layout/fragment_create_new_group.xml
mifosng-android/src/main/res/values/strings.xml

Refactor: create client and added option for mentory fields and optional fields

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/CentersListAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/views/CircularImageView.java
mifosng-android/src/main/java/com/mifos/utils/Utils.java
mifosng-android/src/main/res/drawable/circular_background.xml
mifosng-android/src/main/res/layout/row_center_list_item.xml
mifosng-android/src/main/res/values/strings.xml

CenterList Enhance #390 resolved

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/grouploanaccount/GroupLoanAccountFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java
mifosng-android/src/main/res/layout/fragment_add_loan.xml
mifosng-android/src/main/res/values/strings.xml

Fix: Issue #403 - Dynamically updated nominal interest rate 

---

mifosng-android/src/main/res/layout/fragment_add_loan.xml
mifosng-android/src/main/res/values/strings.xml

fix 402: add labels for loan disbursement and submission date

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/grouploanaccount/GroupLoanAccountFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/AccountLinkingOptions.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/GroupLoanTemplate.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/LoanTemplate.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/RepaymentFrequencyDaysOfWeekTypeOptions.java
mifosng-android/src/main/java/com/mifos/services/data/LoansPayload.java
mifosng-android/src/main/res/layout/fragment_add_loan.xml
mifosng-android/src/main/res/values/strings.xml

Fix: Ideal Loan Template - Added default values for the fields and saving linkage options

---

mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerSavings.java
mifosng-android/src/main/java/com/mifos/api/services/SavingsAccountService.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccount/SavingsAccountFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccount/SavingsAccountMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccount/SavingsAccountPresenter.java
mifosng-android/src/main/java/com/mifos/objects/templates/savings/SavingProductsTemplate.java
mifosng-android/src/main/java/com/mifos/services/data/SavingsPayload.java
mifosng-android/src/main/res/layout/fragment_add_savings_account.xml
mifosng-android/src/main/res/values/strings.xml

Add following fields to the Create Savings Account form #408

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/grouploanaccount/GroupLoanAccountFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/uihelpers/MFDatePicker.java

Fix: Both submission and disbursement dates change (#479)

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/formwidgets/FormToggleButton.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ActivityComponent.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java
mifosng-android/src/main/java/com/mifos/objects/noncore/DataTablePayload.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/LoanTemplate.java
mifosng-android/src/main/java/com/mifos/services/data/LoansPayload.java
mifosng-android/src/main/java/com/mifos/utils/Constants.java
mifosng-android/src/main/java/com/mifos/utils/FragmentConstants.java
mifosng-android/src/main/res/values/dimens.xml
mifosng-android/src/main/res/values/strings.xml

Fix: #466 
Currently added in Client Loan Application only. Adding to the others as well in the meantime.

feat: Add DataTables' generic fragment

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/uihelpers/MFDatePicker.java

Fix: Datepicker picking the wrong date (#489)

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java

Fix491: Client loan independent Disbursement and Submission dates

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java

fix: onclick client loan application submit, fragment retrun to loanaccount from datatable.

---

mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerClient.java
mifosng-android/src/main/java/com/mifos/api/local/databasehelper/DatabaseHelperClient.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/datatablerowdialog/DataTableRowDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncclientpayloads/SyncClientPayloadsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncclientpayloads/SyncClientPayloadsPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListPresenter.java
mifosng-android/src/main/java/com/mifos/objects/client/ClientPayload.java
mifosng-android/src/main/java/com/mifos/objects/noncore/ColumnHeader.java
mifosng-android/src/main/java/com/mifos/objects/noncore/ColumnValue.java
mifosng-android/src/main/java/com/mifos/objects/noncore/DataTable.java
mifosng-android/src/main/java/com/mifos/objects/noncore/DataTablePayload.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/ClientsTemplate.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/Options.java
mifosng-android/src/test/java/com/mifos/mifosxdroid/offline/syncclientpayloads/SyncClientPayloadsPresenterTest.java

fix: offline create client and Datatable feat added.

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/ClientNameListAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/utils/ImageLoaderUtils.java

fix: client image loading fine in client details page and in list

---

mifosng-android/src/main/java/com/mifos/api/BaseApiManager.java
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerRunReport.java
mifosng-android/src/main/java/com/mifos/api/model/APIEndPoint.java
mifosng-android/src/main/java/com/mifos/api/services/RunReportsService.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ActivityComponent.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ApplicationComponent.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/CentersActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerdetails/CenterDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerdetails/CenterDetailsMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerdetails/CenterDetailsPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerlist/CenterListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/grouplist/GroupListFragment.java
mifosng-android/src/main/java/com/mifos/objects/group/CenterInfo.java
mifosng-android/src/main/res/layout/fragment_center_details.xml
mifosng-android/src/main/res/menu/menu_center.xml
mifosng-android/src/main/res/values/strings.xml

feat: center details

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncclientsdialog/SyncClientsDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncgroupsdialog/SyncGroupsDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountapproval/LoanAccountApproval.java
mifosng-android/src/main/res/layout/dialog_fragment_approve_loan.xml

fix: Loan approval and sync in offline mode not syncing

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/core/MifosBaseActivity.java

Fix : Incorrect navigation in CentersActivity

---

mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerClient.java
mifosng-android/src/main/java/com/mifos/api/services/ClientService.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/core/util/Toaster.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ActivityComponent.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/activateclient/ActivateClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/activateclient/ActivateClientMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/activateclient/ActivateClientPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/objects/client/ClientActivate.java
mifosng-android/src/main/java/com/mifos/utils/MFErrorParser.java
mifosng-android/src/main/res/layout/fragment_activate_client.xml
mifosng-android/src/main/res/values/strings.xml

feat: client activation

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncclientsdialog/SyncClientsDialogPresenter.java

fix: Loan synchronization bug

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardActivity.java

fix: clientlist, createclient and dashboard search fragment overlapping

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountPresenter.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/LoanOfficerOptions.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/LoanTemplate.java
mifosng-android/src/main/res/values/strings.xml

fix: LoanAccount Template 

---

mifosng-android/src/main/java/com/mifos/objects/accounts/loan/Summary.java

fix: LoanAccount Summary principalOverdue and feeChargesDueAtDisbursementCharged Int to Double

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccount/SavingsAccountFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccount/SavingsAccountMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccount/SavingsAccountPresenter.java

fix: create savingsaccount failed server message

---

mifosng-android/src/main/java/com/mifos/api/DataManager.java
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerSavings.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ActivityComponent.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingaccountsummary/SavingsAccountSummaryFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingaccountsummary/SavingsAccountSummaryMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingaccountsummary/SavingsAccountSummaryPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccountapproval/SavingsAccountApprovalFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccountapproval/SavingsAccountApprovalMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccountapproval/SavingsAccountApprovalPresenter.java
mifosng-android/src/main/res/layout/dialog_fragment_approve_savings.xml

fix: Savings Account Approval and Activate feature

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/core/MifosBaseActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/activateclient/ActivateClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListPresenter.java
mifosng-android/src/main/java/com/mifos/objects/client/Client.java
mifosng-android/src/main/res/layout/fragment_client_details.xml

fix: fragment transaction and activate client

---

mifosng-android/src/commonTest/java/com/mifos/mifosxdroid/FakeRemoteDataSource.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncclientsdialog/SyncClientsDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncgroupsdialog/SyncGroupsDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncclientpayloads/SyncClientPayloadsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncclientpayloads/SyncClientPayloadsMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncclientpayloads/SyncClientPayloadsPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncgrouppayloads/SyncGroupPayloadsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncgrouppayloads/SyncGroupPayloadsMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncgrouppayloads/SyncGroupPayloadsPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncloanrepaymenttransacition/SyncLoanRepaymentTransactionFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncloanrepaymenttransacition/SyncLoanRepaymentTransactionMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncloanrepaymenttransacition/SyncLoanRepaymentTransactionPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncsavingsaccounttransaction/SyncSavingsAccountTransactionPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListFragment.java
mifosng-android/src/main/java/com/mifos/objects/noncore/DataTable.java
mifosng-android/src/main/java/com/mifos/objects/noncore/DataTablePayload.java
mifosng-android/src/test/java/com/mifos/mifosxdroid/offline/syncclientpayloads/SyncClientPayloadsPresenterTest.java

fix: sync offline client

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerlist/CenterListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupslist/GroupsListFragment.java
mifosng-android/src/main/res/drawable/ic_add_black_24dp.xml
mifosng-android/src/main/res/layout/activity_dashboard.xml
mifosng-android/src/main/res/layout/activity_toolbar_container.xml
mifosng-android/src/main/res/layout/fragment_centers_list.xml
mifosng-android/src/main/res/layout/fragment_client.xml
mifosng-android/src/main/res/layout/fragment_client_search.xml
mifosng-android/src/main/res/layout/fragment_groups.xml

feat: create client, group and center in respective fragment by fab button

---

mifosng-android/src/main/java/com/mifos/api/local/databasehelper/DatabaseHelperClient.java
mifosng-android/src/main/java/com/mifos/utils/MapDeserializer.java

fix: MapDeserializer for deserializing the long int string and double

---

mifosng-android/build.gradle
mifosng-android/src/main/AndroidManifest.xml
mifosng-android/src/main/java/com/mifos/App.java

fix: crashanalytics for logging the crash report

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/ClientNameListAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/GroupNameListAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupslist/GroupsListFragment.java
mifosng-android/src/main/res/layout/row_client_name.xml
mifosng-android/src/main/res/layout/row_group_name.xml

fix: client and group item view size

---

.travis.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
mifosng-android/build.gradle

chore: gradle version, supportlibrary version, gradle wrapper 2.11 to 2.14.1 and build tool version updated

---

mifosng-android/src/main/res/layout/row_center_list_item.xml
mifosng-android/src/main/res/layout/row_client_name.xml
mifosng-android/src/main/res/layout/row_group_name.xml

fix: center item view wrap_content

---

mifosng-android/src/main/java/com/mifos/api/DataManager.java
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerAuth.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ApplicationComponent.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/login/LoginActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/login/LoginMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/login/LoginPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardActivity.java
mifosng-android/src/main/res/layout/view_nav_drawer_header.xml
mifosng-android/src/main/res/values/strings.xml

fix: login show Connection Status

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/PathTrackingAdapter.java

fix: Path Tracker crashes the app if GPS is turned off (#527)

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupdetails/GroupDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupdetails/GroupDetailsMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupdetails/GroupDetailsPresenter.java
mifosng-android/src/main/res/layout/item_data_table.xml
mifosng-android/src/main/res/menu/menu_group.xml
mifosng-android/src/main/res/values/strings.xml

feat: group more info

---

mifosng-android/src/main/java/com/mifos/api/DataManager.java
mifosng-android/src/main/java/com/mifos/api/services/ChargeService.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/chargedialog/ChargeDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/chargedialog/ChargeDialogMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/chargedialog/ChargeDialogPresenter.java
mifosng-android/src/main/java/com/mifos/objects/client/ChargeCalculationType.java
mifosng-android/src/main/java/com/mifos/objects/client/Charges.java
mifosng-android/src/main/java/com/mifos/objects/client/ClientDate.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/ChargeAppliesTo.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/ChargeCalculationType.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/ChargeOptions.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/ChargePaymentMode.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/ChargeTemplate.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/ChargeTimeType.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/Currency.java
mifosng-android/src/main/java/com/mifos/objects/templates/clients/IncomeOrLiabilityAccount.java

Add API Response Model in ChargeDialogeFragment

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/grouplist/GroupListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/grouplist/GroupListMvpView.java
mifosng-android/src/main/res/layout/fragment_group_list.xml
mifosng-android/src/main/res/values/strings.xml

Add empty message if no groups available

---

mifosng-android/build.gradle
mifosng-android/src/main/AndroidManifest.xml

release: Mifos android-client 1.0.0

---

mifosng-android/src/main/java/com/mifos/api/services/LoanService.java
mifosng-android/src/main/java/com/mifos/objects/accounts/loan/Summary.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/LoanRepaymentTemplate.java

fix: client sync due money ammount

---

mifosng-android/src/main/res/layout/dialog_fragment_document.xml

fix: edittext overflow in dialog box

---

mifosng-android/build.gradle
mifosng-android/src/main/res/layout/row_document_list.xml

release: Mifos android-client build 1.0.1

---

mifosng-android/src/main/java/com/mifos/api/services/OfficeService.java
mifosng-android/src/main/java/com/mifos/api/services/StaffService.java
mifosng-android/src/main/java/com/mifos/services/data/SavingsPayload.java

style: Unnessasary semi-colons present in certain Java files

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerdetails/CenterDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupdetails/GroupDetailsFragment.java
mifosng-android/src/main/java/com/mifos/utils/Utils.java

Fix converting date to medium format.

---

mifosng-android/src/main/res/layout/fragment_survey_question.xml

style: Questions in the survey are not being properly displayed.

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardActivity.java

fix-659: App crashes on RTL locales

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientcharge/ClientChargeFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientcharge/ClientChargeMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientcharge/ClientChargePresenter.java

Fix: Failed to load Charges text and icon not visible when no charges available #643

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupFragment.java

Fix: Toast message on Group creation not correct #608

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupFragment.java

fix: Empty toast message is displayed when user clicks on "Submit" button in the Create Group Fragment in the absence of Internet connection.

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ActivityComponent.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingaccountsummary/SavingsAccountSummaryFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingaccountsummary/SavingsAccountSummaryPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccountactivate/SavingsAccountActivateFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccountactivate/SavingsAccountActivateMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccountactivate/SavingsAccountActivatePresenter.java
mifosng-android/src/main/res/values/strings.xml

Fix #679 
(Tested on one saving account. I'll do testing on other accounts after setting the backend on the localhost.)

Feat: Add date option while activating savings

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientFragment.java

fix 678: Unable to create client

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java
mifosng-android/src/main/res/layout/fragment_add_loan.xml

Fix: Add 'Loan term frequency type' option

---

mifosng-android/src/main/res/layout/item_offline_dashboard.xml

style: Payload name and payload count overlap for transactions in the offline dashboard fragment

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountdisbursement/LoanAccountDisbursementFragment.java

fix: Empty Snackbar is displyed on tapping "Submit" button in the Disburse Loan Dialog fragment in the absence of Internet connection

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveysubmit/SurveySubmitFragment.java

fix: App Crashs while navigating through the survey

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccount/SavingsAccountFragment.java

fix: Snackbar with no text is displayed when the user loses Internet connectivity in the Add Savings Account Fragment

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountapproval/LoanAccountApproval.java

fix: Loan gets approved in spite of "Approved Amount" and "Transaction Amount" field being blank

---

mifosng-android/src/main/res/layout/dialog_fragment_approve_loan.xml

The issue #645 is Fixed!
I have just added a scrollbar to the xml as needed.
- [Not Tick as I didn't Found this XML ] Apply the `MifosStyle.xml` style template to your code in Android Studio.
- [Tick] Run the unit tests with `./gradlew check` to make sure you didn't break anything
- [Tick] If you have multiple commits please combine them into one commit by squashing them.

Fix #645 :Added Scrollbar to Load Account Approval Fragment's Xml

---

mifosng-android/src/main/java/com/mifos/utils/CheckSelfPermissionAndRequest.java
mifosng-android/src/main/res/values/strings.xml

fix: App crashes if 'Never Ask again' is selected while asking for permission

---

build.gradle
mifosng-android/build.gradle
mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ActivityComponent.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/sign/SignatureFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/sign/SignatureMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/sign/SignaturePresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/views/SignatureView.java
mifosng-android/src/main/res/layout/fragment_sign.xml
mifosng-android/src/main/res/menu/sign_bottom_navbar.xml
mifosng-android/src/main/res/menu/signature_menu.xml
mifosng-android/src/main/res/values/strings.xml

Add Capture and Upload Sign feature

---

mifosng-android/build.gradle

Apk Size Increased drastically after using JNI

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java

fix: LoanTermFrequencyType overriding enabled

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/ClientNameListAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListFragment.java

fix: update client profile image, when user come client details activity

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncgroupsdialog/SyncGroupsDialogPresenter.java

Fix: group sync failed for some groups

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncclientsdialog/SyncClientsDialogPresenter.java

Fix: client sync failed for some clients

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/identifierdialog/IdentifierDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientidentifiers/ClientIdentifiersPresenter.java

Resolves #768 #648 (duplicate of #768)

Fix: resolved identifier issues

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientFragment.java

Fix: allow client name less than 4 characters

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/sign/SignatureFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/views/SignatureView.java
mifosng-android/src/main/res/values/strings.xml

Fix:Empty Signature Uploads

---

.github/ISSUE_TEMPLATE.md

Issue:#838
- \[x] Apply the `MifosStyle.xml` style template to your code in Android Studio.
- \[x] Run the unit tests with `./gradlew check` to make sure you didn't break anything
- \[x] If you have multiple commits please combine them into one commit by squashing them.

Fix Issue #838 : Fixed typos is Issue Template

---

mifosng-android/src/main/java/com/mifos/api/DataManager.java
mifosng-android/src/main/java/com/mifos/api/services/ChargeService.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/chargedialog/ChargeDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/chargedialog/ChargeDialogMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/chargedialog/ChargeDialogPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/chargedialog/OnChargeCreateListener.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/loanchargedialog/LoanChargeDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/loanchargedialog/LoanChargeDialogMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/loanchargedialog/LoanChargeDialogPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientcharge/ClientChargeFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientcharge/ClientChargePresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loancharge/LoanChargeFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loancharge/LoanChargePresenter.java
mifosng-android/src/main/java/com/mifos/objects/client/ChargeCreationResponse.java
mifosng-android/src/main/java/com/mifos/utils/DateHelper.java
mifosng-android/src/main/res/layout/row_charge_name.xml
mifosng-android/src/main/res/values/strings.xml
mifosng-android/src/test/java/com/mifos/mifosxdroid/online/ClientChargePresenterTest.java
mifosng-android/src/test/java/com/mifos/mifosxdroid/online/LoanChargePresenterTest.java

Removed redundant GET calls from Client charges and Loan account charges screen

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/grouploanaccount/GroupLoanAccountFragment.java
mifosng-android/src/main/java/com/mifos/objects/templates/loans/GroupLoanTemplate.java
mifosng-android/src/main/java/com/mifos/services/data/GroupLoanPayload.java

Fix #453 
Layout implemented in this fix:

feat: Ideal Group Loan Template

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/uihelpers/MFDatePicker.java
mifosng-android/src/main/res/values/styles.xml

Fix #920 Datepicker buttons visible

---

mifosng-android/src/main/res/layout/fragment_client_search.xml

fix: changes list width to entire screen

---

mifosng-android/src/main/res/layout/fragment_client.xml

Fix #917:Extra Blue Bar in group listings in centers

---

mifosng-android/src/main/res/drawable/ic_assignment_black_24dp.xml
mifosng-android/src/main/res/menu/menu_nav_drawer.xml

- \[x] Apply the `MifosStyle.xml` style template to your code in Android Studio.
- \[x] Run the unit tests with `./gradlew check` to make sure you didn't break anything
- \[x] If you have multiple commits please combine them into one commit by squashing them.
**ScreenShot**

fix:Added icons for collection and individual collection sheet

---

mifosng-android/src/main/res/layout/fragment_client_search.xml
mifosng-android/src/main/res/layout/fragment_create_new_center.xml
mifosng-android/src/main/res/layout/fragment_create_new_client.xml
mifosng-android/src/main/res/layout/fragment_create_new_group.xml

fix #974 
@therajanmaurya  @tarun0  Please review

fix #974:Inconsistent check boxes

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientcharge/ClientChargePresenter.java

Fix #957 Non empty charges list in offline mode

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientFragment.java

fix #955 
@therajanmaurya Please review.

fix #955:Inconsistent client Payload behaviour

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/documentdialog/DocumentDialogFragment.java
mifosng-android/src/main/res/layout/dialog_fragment_document.xml

fix : keyboard next click in upload dialog

---

.travis.yml
build.gradle
mifosng-android/build.gradle

Fix #993:Updating gradle dependancies

---

mifosng-android/build.gradle
mifosng-android/src/main/java/com/mifos/mifosxdroid/activity/pathtracking/PathTrackingActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerlist/CenterListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerlist/CenterListPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupslist/GroupsListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupslist/GroupsListPresenter.java
mifosng-android/src/main/res/layout/activity_dashboard.xml
mifosng-android/src/main/res/layout/activity_path_tracker.xml
mifosng-android/src/main/res/layout/fragment_centers_list.xml
mifosng-android/src/main/res/layout/fragment_client.xml
mifosng-android/src/main/res/layout/fragment_client_search.xml
mifosng-android/src/main/res/layout/fragment_create_new_center.xml
mifosng-android/src/main/res/layout/fragment_create_new_client.xml
mifosng-android/src/main/res/layout/fragment_create_new_group.xml
mifosng-android/src/main/res/layout/fragment_groups.xml
mifosng-android/src/main/res/layout/fragment_offline_dashboard.xml
mifosng-android/src/test/java/com/mifos/mifosxdroid/online/CenterListPresenterTest.java
mifosng-android/src/test/java/com/mifos/mifosxdroid/online/ClientListPresenterTest.java
mifosng-android/src/test/java/com/mifos/mifosxdroid/online/GroupsListPresenterTest.java

Fix #946 
@therajanmaurya @tarun0  Please review.

feat : added sweet-error for handling UI errors

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/ClientNameListAdapter.java

Fix #774 
@therajanmaurya @tarun0  Please review.No client is being displayed as null now.
The Json response of the client being displayed as null and the other can clearly be seen the json response captured in the gist.
https://gist.github.com/AkshGautam/2295e7304b9d0a32d75110e2d677eebb

Fix Issue #774: Client Name is displayed as null

---

mifosng-android/src/main/AndroidManifest.xml
mifosng-android/src/main/res/drawable/background.xml
mifosng-android/src/main/res/values/colors.xml
mifosng-android/src/main/res/values/styles.xml

fix #925 
@therajanmaurya @tarun0  Please review.

fix #925:Adding splash screen

---

Contributing.md

Adding: Contributing Guidelines

---

build.gradle

Fix #1005: Update okHttp version

---

mifosng-android/src/main/res/menu/menu_nav_drawer.xml

Fixes #999 
Before the change:
After the change:

Added Run Reports icon

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/PathTrackingAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/uihelpers/MFDatePicker.java

Refactor: String manipulation in Date done using DateFormat

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientPresenter.java

Fix-Issue#823 :Improper Layout Inflation

---

mifosng-android/src/main/java/com/mifos/utils/ValidationUtil.java

Fix: allow numbers in name

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/generatecollectionsheet/GenerateCollectionSheetFragment.java
mifosng-android/src/main/java/com/mifos/utils/MFErrorParser.java
mifosng-android/src/main/res/values/strings.xml

Fix :issue #791 - Invalid Toast Message

---

mifosng-android/src/main/res/layout/fragment_centers_list.xml
mifosng-android/src/main/res/layout/fragment_client.xml
mifosng-android/src/main/res/layout/fragment_groups.xml

fix: Issue #778 - Added simple Scrollbar for clients/groups/centers list

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupdetails/GroupDetailsFragment.java
mifosng-android/src/main/res/menu/menu_group.xml

Add ability to create group saving account [MIFOSAC-130]

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/activate/ActivateFragment.java

Fix: Issue #810- Invalid Group/client/center Toast message

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewcenter/CreateNewCenterFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupFragment.java

Fix: #Issue 814-Unsorted Drop Downs

---

mifosng-android/src/main/AndroidManifest.xml

**Issue Reference :**
#802 
**After fixing the issue :**

fix: App crashes when the screen is tilted to landscape mode

---

mifosng-android/src/main/res/values/strings.xml

fix: Typo in Collection Sheet

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/login/LoginActivity.java

Keyboard disappear on clicking the login button

---

mifosng-android/src/main/res/values-sw/strings.xml

Add support for Swahili

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/core/MifosBaseActivity.java

Hide soft keyboard on clicking the login button

---

mifosng-android/src/main/AndroidManifest.xml

Fixes #1008 
Test APK:
[mifosng-android-debug.apk.zip](https://github.com/openMF/android-client/files/2730284/mifosng-android-debug.apk.zip)
- [ Not tick as I didn't find it ] Apply the `MifosStyle.xml` style template to your code in Android Studio.

Fixes #1008 Readability issue with StatusBar

---

mifosng-android/src/main/res/values/strings.xml

Fix #1019 - Generate Collection String

---

mifosng-android/build.gradle
mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/LoanListAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/MifosGroupListAdapter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/core/MifosBaseActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/core/ProgressableDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/core/ProgressableFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/core/util/Toaster.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/RunReportsActivity.java

Fixes #1091 
Removed redundant type casts from various java files to make the code look cleaner.

Removed redundant type casts.

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/objects/client/Client.java
mifosng-android/src/main/res/layout/fragment_client_details.xml

Feat: Added Mobile No. field to Client Details Screen

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/documentdialog/DocumentDialogFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/documentdialog/DocumentDialogMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/documentdialog/DocumentDialogPresenter.java
mifosng-android/src/main/res/layout/dialog_fragment_document.xml

fix: Cannot select the document for identifiers.

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupslist/GroupsListFragment.java

fix: sort groups list

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/core/MifosBaseActivity.java

fix #1219: app crashes on drawer click

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/DashboardActivity.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListFragment.java
mifosng-android/src/main/res/layout/fragment_client.xml

fix: NavBar overshadowed by progressBar

---

mifosng-android/src/main/res/layout/fragment_client_details.xml

Added margin to client activity

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewclient/CreateNewClientPresenter.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListMvpView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListPresenter.java
mifosng-android/src/main/res/values/strings.xml

fix: maker checker condition handling

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.java
mifosng-android/src/main/java/com/mifos/objects/client/Client.java
mifosng-android/src/main/res/layout/fragment_client_details.xml

Feat: Added feature to show group names in the Client Details screen.

---

mifosng-android/src/main/res/layout/activity_login.xml

Fixes #1330  After toggling **Connection Settings** a smooth transition is shown

Fix #1330: No smooth transition after opening connection settings while logging in

---

mifosng-android/src/main/res/layout/activity_login.xml

Fixes #1491 
Added inputType attribute to instance URL EditText

fix 1491: added inputType to instance URL EditText

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerdetails/CenterDetailsFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupdetails/GroupDetailsFragment.java
mifosng-android/src/main/res/values/strings.xml

Fix #891 
@therajanmaurya @tarun0 Please reveiw.
**empty staff name fix**
**empty external ID fix**

Fix Issue #891:Empty space when no staff associated in center and no External ID in group

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java

Fix #1460: Removed unnecessary String conversions

---

mifosng-android/src/main/java/com/mifos/objects/PaymentTypeOption.java

Fixed #1497: Using compare() method to compare numbers

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/core/RecyclerItemClickListener.java

Fix #1462: Removed unnecessary interface modifiers

---

mifosng-android/src/main/res/layout/activity_login.xml

Fix: Jump next EditText while login

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/views/CircularImageView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/views/FontTextView.java

Fixes #1446 
- [x ] Apply the `MifosStyle.xml` style template to your code in Android Studio.
- [ x] Run the unit tests with `./gradlew check` to make sure you didn't break anything
- [ x] If you have multiple commits please combine them into one commit by squashing them.

fix: Android X migration warnings

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveysubmit/SurveySubmitFragment.java

Fix: ProgressBar in submit survey.

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/loanchargedialog/LoanChargeDialogFragment.java

Fixes #1420 
- [ 👍 ] Apply the `MifosStyle.xml` style template to your code in Android Studio.
- [ 👍 ] Run the unit tests with `./gradlew check` to make sure you didn't break anything
- [ 👍 ] If you have multiple commits please combine them into one commit by squashing them.

fix : Removed Unnecessary variable declaration

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/loanchargedialog/LoanChargeDialogFragment.java

fix : Removed empty conditional

---

mifosng-android/src/main/res/layout/row_center_list_item.xml

fix 1430: Redundant namespace declaration

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.java

Fixes #1281 Fixed null value in client activity toolbar

fix 1281: Null value in Client Activity toolbar

---

mifosng-android/src/main/res/layout/row_charge_name.xml

Fix: charges text aligned

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/uihelpers/MFDatePicker.java

fix #1384: Removed redundant public modifier

---

mifosng-android/src/main/AndroidManifest.xml

Fix #918 
@tarun0 @therajanmaurya @luckyman20  Please review.
To match the application standard behavior where most of the activities have orientation fixed as portrait, I have fixed the orientation to portrait. Please comment if I need to make changes to make fixes by retaining the state on orientation changes.

Fix #918:Reduction in toolbar text and Recreation of activity on orientation changes.

---

mifosng-android/src/main/res/layout/activity_dashboard.xml

Fix: White space removed

---

mifosng-android/src/main/java/com/mifos/objects/client/PageItem.java

Removes redundant string operations

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/runreports/report/ReportFragment.java

Corrected Toast in Report Fragment by adding .show() method

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/SettingsFragment.java

Deleted all unused import statements

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/activity/pathtracking/PathTrackingActivity.java

Fix #565 Locations sorted according to date in pathTracker

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingaccountsummary/SavingsAccountSummaryFragment.java

Fix:Wrong Toolbar title in Savings Account summary

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/documentlist/DocumentListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveylist/SurveyListFragment.java

fix:#876
- \[x] Apply the `MifosStyle.xml` style template to your code in Android Studio.
- \[x] Run the unit tests with `./gradlew check` to make sure you didn't break anything
- \[x] If you have multiple commits please combine them into one commit by squashing them.
**ScreenShots**

fix:Issue#876:Corrected labelling of toolbar in client documents,surveys

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/documentlist/DocumentListFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/documentlist/DocumentListPresenter.java
mifosng-android/src/test/java/com/mifos/mifosxdroid/online/DocumentListPresenterTest.java

Fix: Delete elements from document list in identifier

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/core/MifosBaseActivity.java
mifosng-android/src/main/res/values/strings.xml

Fix: Successful logout message

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccountactivate/SavingsAccountActivatePresenter.java

fix #1386: No progress dialog for Savings Account Activation

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/passcode/PassCodeActivity.java
mifosng-android/src/main/res/values/strings.xml

Fix 1079 Message is displayed when user is successfully signed in

---

README.md

Readme updated as the previous readme.md is not up to date.

 Readme update

---

.github/workflows/android.yml

This PR addresses #1557. Created android.yml file for setting up GitHub Actions for Android Client.

Fix #1557: Set up GitHub Actions as CI/CD for Android Client

---

mifosng-android/build.gradle

minor bug  fixed

---

mifosng-android/build.gradle

minor bug fixed

---

mifosng-android/src/main/res/drawable/gradient_repayment.xml
mifosng-android/src/main/res/drawable/gradient_spinner.xml
mifosng-android/src/main/res/drawable/login_button_rounded.xml
mifosng-android/src/main/res/layout/activity_login.xml
mifosng-android/src/main/res/layout/fragment_client_details.xml
mifosng-android/src/main/res/layout/fragment_client_search.xml
mifosng-android/src/main/res/layout/fragment_new_collection_sheet.xml
mifosng-android/src/main/res/values/colors.xml
mifosng-android/src/main/res/values/dimens.xml
mifosng-android/src/main/res/values/styles.xml
mifosng-android/src/main/res/values/styles_text.xml

Enhancement: UI enhance for login, dashboard, client details, individual collection sheet. 

---

mifosng-android/src/instrumentTest/java/com/mifos/mifosxdroid/tests/SurveyQuestionViewPagerActivityTest.java
mifosng-android/src/main/AndroidManifest.xml
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/SurveyQuestionActivity.kt

Fix: Up button in Survey question page

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/search/SearchFragment.java

Fixes #1740  and #1738
https://user-images.githubusercontent.com/67901968/107414984-c907bc00-6b38-11eb-9d28-2ac3c6d9c827.mp4

Fixes #1740 and #1738: Snackbar added and unnecessary search results removed

---

mifosng-android/build.gradle
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/search/SearchFragment.java
mifosng-android/src/main/java/com/mifos/utils/PrefManager.java
mifosng-android/src/main/res/values/strings.xml

Fixes #1614 Intro added in SearchFragment

---

mifosng-android/src/instrumentTest/java/com/mifos/mifosxdroid/tests/SavingsAccountSummaryFragmentTest.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ActivityComponent.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingaccountsummary/SavingsAccountSummaryFragment.kt
mifosng-android/src/main/res/layout/transaction_detail_dialog_layout.xml
mifosng-android/src/main/res/values/strings.xml
mifosng-android/src/main/res/values/styles_table.xml

Fixes #1690 Transaction details layout added

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ActivityComponent.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/collectionsheetindividualdetails/PaymentDetailsFragment.kt
mifosng-android/src/main/res/layout/individual_collections_sheet_details.xml

Fixes #1653 
https://user-images.githubusercontent.com/31315800/102746711-ce405a00-4384-11eb-9db7-2a1c69d1dcf3.mp4

Fixes #1653 visibility of info text fixed in individual collection sheet

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingaccountsummary/SavingsAccountSummaryPresenter.kt

Fixes #1590 Toast corrected when no internet connectivity in SavingAccountsSummary

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/component/ActivityComponent.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerlist/CenterListFragment.kt

Fixes #1568 
**Screen Recording**

Fixes #1568 Infinite refresh issue resolved

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/runreports/report/ReportFragment.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/views/scrollview/CustomScrollView.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/views/scrollview/ScrollChangeListener.java
mifosng-android/src/main/res/layout/fragment_client_report.xml

Fixes #1682 
https://user-images.githubusercontent.com/31315800/103179015-f7de1180-48ad-11eb-8c0e-8334adda5f9e.mp4

Fixes #1682 Paginated the report result in ReportDetailFragment

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/SettingsFragment.kt
mifosng-android/src/main/res/drawable/ic_baseline_edit_24.xml
mifosng-android/src/main/res/values/strings.xml
mifosng-android/src/main/res/xml/preferences.xml

Fixes #1610 InstanceURl edit preference added in settings

---

mifosng-android/src/main/java/com/mifos/utils/LanguageHelper.java

Language setting change fixed

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/searchdialog/SearchDialog.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/collectionsheetindividual/NewIndividualCollectionSheetFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/views/CustomSpinner.java
mifosng-android/src/main/res/drawable/round_outline_bg.xml
mifosng-android/src/main/res/layout/fragment_new_collection_sheet.xml
mifosng-android/src/main/res/layout/search_list_dialog_layout.xml

Fixes #1671 
https://user-images.githubusercontent.com/31315800/103141115-93884a00-4715-11eb-838f-480974791640.mp4

Fixes #1671 Search functionality added in individual collection sheet

---

.github/workflows/android.yml

Fix: cache for GitHub Actions

---

.github/workflows/android.yml

Fix: distinct jobs for gradle tasks in github actions

---

mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerGroups.java
mifosng-android/src/main/java/com/mifos/api/mappers/accounts/loan/LoanAccMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/accounts/loan/LoanAccStatusMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/accounts/loan/LoanAccTypeMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/accounts/savings/SavingsAccCurrencyMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/accounts/savings/SavingsAccMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/accounts/savings/SavingsAccStatusMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/groups/CreateGroupRequestMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/groups/CreateGroupResponseMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/groups/GetGroupsGroupIdAccountsMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/groups/GetGroupsGroupIdMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/groups/GetGroupsPagedItemsMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/groups/GetPagedGroupsResponseMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/groups/GroupsTimelineMapper.kt
mifosng-android/src/main/java/com/mifos/api/utils/extesnions.kt

Description
Integrated /groups related endpoint using sdk. All the Fineract related areas are commented out with `// todo:` please check them and refer both swagger as well as old html docs for getting better idea of the issues.

groups endpoint sdk integration

---

mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerCenter.java
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerCharge.java
mifosng-android/src/main/java/com/mifos/api/mappers/accounts/savings/SavingsAccCurrencyMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/accounts/savings/SavingsAccMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/accounts/savings/SavingsAccStatusMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/centers/CentersPageItemsMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/centers/GetCentersCenterIdResponseMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/centers/GetCentersResponseMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/office/GetOfficeResponseMapper.kt

Description
- list centers integrated
- fetch centers accounts integrated
- getCentersGroupAndMeeting remaining see line 128 of DataManagerCenter
Bugs
- centers/{centerId}?association endpoint missing
- activationDate,dateFormat,locale etc. fields missing in PostCentersRequest while creating centre

centers endpoint integrated

---

mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerSurveys.java
mifosng-android/src/main/java/com/mifos/api/mappers/survey/QuestionDataMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/survey/ScorecardDataMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/survey/SurveyDataMapper.kt

integrated survey endpoints

---

build.gradle
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerAuth.java
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerClient.java
mifosng-android/src/main/java/com/mifos/api/mappers/client/ClientActivatingRequestMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/client/ClientsClientIdResponseMapper.kt
mifosng-android/src/main/java/com/mifos/api/mappers/client/PostClientRequestMapper.kt
mifosng-android/src/main/java/com/mifos/objects/client/ActivatePayload.java

Updates 
- Updated fineract-android-sdk version `1.0.0` to `1.0.1`
- New body payload while authenticating.
- Client activation fixed.

sdk version updated, and introduced related updates

---

mifosng-android/src/main/res/layout/dialog_fragment_approve_savings.xml

Fixes #1768: UI Enhancements done in SavingsAccountActivateFragment

---

mifosng-android/src/main/java/com/mifos/utils/ValidationUtil.java

Fix: Client name only contains alphabets

---

build.gradle
mifosng-android/build.gradle
mifosng-android/src/main/res/values/styles.xml

Build fails due to a dependency on bintray

---

mifosng-android/src/main/res/layout/row_account_item.xml
mifosng-android/src/main/res/layout/row_center_item.xml
mifosng-android/src/main/res/layout/row_center_list_item.xml
mifosng-android/src/main/res/layout/row_charge_name.xml
mifosng-android/src/main/res/layout/row_client_list_item.xml
mifosng-android/src/main/res/layout/row_client_name.xml
mifosng-android/src/main/res/layout/row_collection_list_group.xml
mifosng-android/src/main/res/layout/row_collection_list_group_client.xml
mifosng-android/src/main/res/layout/row_collection_sheet_loan.xml
mifosng-android/src/main/res/layout/row_document_list.xml
mifosng-android/src/main/res/layout/row_group_list.xml
mifosng-android/src/main/res/layout/row_group_list_item.xml
mifosng-android/src/main/res/layout/row_group_name.xml
mifosng-android/src/main/res/layout/row_identifier_list.xml
mifosng-android/src/main/res/layout/row_loan_list_item.xml
mifosng-android/src/main/res/layout/row_loan_repayment_schedule.xml
mifosng-android/src/main/res/layout/row_loan_transaction_item.xml
mifosng-android/src/main/res/layout/row_loan_transaction_item_detail.xml
mifosng-android/src/main/res/layout/row_savings_transaction_item.xml
mifosng-android/src/main/res/layout/row_surveys_list_item.xml
mifosng-android/src/main/res/layout/row_sync_payload.xml
mifosng-android/src/main/res/layout/search_list_dialog_layout.xml
mifosng-android/src/main/res/layout/simple_spinner_item.xml
mifosng-android/src/main/res/layout/sync_progress.xml
mifosng-android/src/main/res/layout/toolbar.xml
mifosng-android/src/main/res/layout/transaction_detail_dialog_layout.xml
mifosng-android/src/main/res/layout/view_account_accordion_section.xml
mifosng-android/src/main/res/layout/view_nav_drawer_header.xml

restructured: xml files for regex row*.xml and util files

---

mifosng-android/src/main/res/layout/activity_about.xml
mifosng-android/src/main/res/layout/activity_center_list.xml
mifosng-android/src/main/res/layout/activity_client_search.xml
mifosng-android/src/main/res/layout/activity_dashboard.xml
mifosng-android/src/main/res/layout/activity_group.xml
mifosng-android/src/main/res/layout/activity_home.xml
mifosng-android/src/main/res/layout/activity_login.xml
mifosng-android/src/main/res/layout/activity_path_tracker.xml
mifosng-android/src/main/res/layout/activity_pinpoint_location.xml
mifosng-android/src/main/res/layout/activity_survey_question.xml
mifosng-android/src/main/res/layout/activity_toolbar_container.xml
mifosng-android/src/main/res/layout/add_payment_detail.xml
mifosng-android/src/main/res/layout/checker_inbox_tasks_fragment.xml
mifosng-android/src/main/res/layout/dash_board_row_progress_bar.xml
mifosng-android/src/main/res/layout/dialog_fragment_add_entry_to_datatable.xml
mifosng-android/src/main/res/layout/dialog_fragment_approve_loan.xml
mifosng-android/src/main/res/layout/dialog_fragment_approve_savings.xml
mifosng-android/src/main/res/layout/dialog_fragment_charge.xml
mifosng-android/src/main/res/layout/dialog_fragment_checker_task_filter.xml
mifosng-android/src/main/res/layout/dialog_fragment_disburse_loan.xml
mifosng-android/src/main/res/layout/dialog_fragment_document.xml
mifosng-android/src/main/res/layout/dialog_fragment_identifier.xml
mifosng-android/src/main/res/layout/dialog_fragment_sync_centers.xml
mifosng-android/src/main/res/layout/dialog_fragment_sync_clients.xml
mifosng-android/src/main/res/layout/dialog_fragment_sync_groups.xml
mifosng-android/src/main/res/layout/dialog_fragment_sync_surveys.xml

restructured: xml files for regex activity*.xml and dialog*.xml

---

.github/workflows/android.yml

Fixes #1889, #1813
Continuation #1888 

Issue 1889

---

mifosng-android/src/main/res/layout/activity_home.xml

Fixes #1896 
https://user-images.githubusercontent.com/94394661/221224305-f9591083-30c5-4acc-ac9e-5441db116f7f.mp4

Fixed the crashing of app after entering the passcode

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientdetails/ClientDetailsFragment.kt

Fixes #1704
https://github.com/openMF/android-client/assets/94394661/1e1493b2-3632-4398-96bd-9a157c3eb6e2

Fix #1704 : Visibility check added to list of accounts in ClientDetailsFragment

---

mifosng-android/src/main/res/layout/checker_inbox_fragment.xml

Fixes #1756 
https://user-images.githubusercontent.com/70195106/107259146-aa36f600-6a62-11eb-8b06-9749886485cd.mp4

Fixes_#1756: Scrolling SearchBox behaviour applied to checker_inbox_fragment

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/HomeActivity.kt
mifosng-android/src/main/res/menu/menu_nav_drawer.xml

Fixes #1910 
https://user-images.githubusercontent.com/94394661/222144909-9e09ddc3-1ba8-4d6c-a154-611b54f053b2.mp4

After returning to the home screen, the navigation drawer becomes unselected

---

mifosng-android/src/main/res/layout/activity_home.xml

Fixes #1898 
https://user-images.githubusercontent.com/94394661/227785299-06274130-1e43-4e8d-a231-a6901e2c0a2d.mp4

Bottom navigation bar now visible in a dark mode

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/SettingsActivity.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/SettingsFragment.kt

Fixes #1908 
https://user-images.githubusercontent.com/94394661/227775633-eaa8ad89-a334-4737-ba1c-03a7bd83de59.mp4

Fixed activity overlays on another activity

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/core/MaterialDialog.java
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/checkertaskfilterdialog/CheckerTaskFilterDialogFragment.kt

Resolve build fail

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/centerlist/CenterListFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupslist/GroupsListFragment.kt

Fixes #1928 
https://user-images.githubusercontent.com/94394661/229445823-9cd7f9f8-ab08-4a30-a9fa-e5fdfc616fbd.mp4

fixed unexpected behavior of the floating button

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupdetails/GroupDetailsFragment.kt

Fixes #1708 
https://github.com/openMF/android-client/assets/94394661/3623ccd5-6f6b-4e33-a26b-43886aeac722

fixes #1708 : Visibility check added to list of accounts in GroupDetailsFragment

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/search/SearchFragment.java
mifosng-android/src/main/res/layout/fragment_client_search.xml

Fixes #1714 
https://github.com/openMF/android-client/assets/94394661/6fdabf28-c69f-42ba-b935-3f30eba188a4

Fixes #1714 : Done key is also made to search in Dashboard Activity

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/core/util/Toaster.java

Fixes #1893 : Fixed snackbar text color

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/runreports/report/ReportFragment.java
mifosng-android/src/main/res/values/strings.xml

Fixes #1683 
https://github.com/openMF/android-client/assets/94394661/016ec7ae-d426-43c1-9a3b-55914a210737

Fixes #1683 : Export CSV feature added in reports

---

mifosng-android/src/main/res/layout/view_account_accordion_section_loan.xml
mifosng-android/src/main/res/layout/view_account_accordion_section_recurring.xml

475
- [check] Apply the `MifosStyle.xml` style template to your code in Android Studio.
- [check] Run the unit tests with `./gradlew check` to make sure you didn't break anything
- [check] If you have multiple commits please combine them into one commit by squashing them.

fix #475 - incorrect content on client screen on no internet connection

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/datatablerowdialog/DataTableRowDialogFragment.java

Fixes #1418 
- [ 👍 ] Apply the `MifosStyle.xml` style template to your code in Android Studio.
- [ 👍 ] Run the unit tests with `./gradlew check` to make sure you didn't break anything
- [ 👍 ] If you have multiple commits please combine them into one commit by squashing them.

feat : Changed the conditions to a switch statement

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/runreports/reportdetail/ReportDetailFragment.java

Fix #1472: Start Date and End Date bug

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/search/SearchPresenter.java

Fixes #1580 network check added before initiating search api call

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/documentdialog/DocumentDialogPresenter.java

Fix: Toast message appeared in upload Document

---

mifosng-android/build.gradle
mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/CheckerTaskListAdapter.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/checkertaskfilterdialog/CheckerTaskFilterDialogFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/checkerinbox/CheckerInboxFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/checkerinbox/CheckerInboxTasksFragment.kt
mifosng-android/src/main/res/layout-land/fragment_client_identifiers.xml
mifosng-android/src/main/res/layout/fragment_client_identifiers.xml

Fixes #1962 : Kotlin version upgrade

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/RunReportsActivity.java

Fixes #1775 
https://user-images.githubusercontent.com/70195106/107977297-dca39e80-6fe0-11eb-8403-ce1b3172512c.mp4

Fixes #1775: Spinner error fixed in RunReportsActivity

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/search/SearchFragment.java
mifosng-android/src/main/res/values-fr/strings.xml
mifosng-android/src/main/res/values-hi/strings.xml
mifosng-android/src/main/res/values-sw/strings.xml
mifosng-android/src/main/res/values-zh/strings.xml
mifosng-android/src/main/res/values/strings.xml

Fixes #1606 added Centers search in searchFragment

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/uihelpers/MFDatePicker.java

Fixes #1638 : Error in Disburment datepicker in Loan Account fragment fixed

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/GroupsActivity.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupdetails/GroupDetailsFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/groupdetails/GroupDetailsMvpView.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/grouploanaccount/GroupLoanAccountFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountsummary/LoanAccountSummaryFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/views/CircularImageView.kt
mifosng-android/src/main/res/layout/activity_home.xml
mifosng-android/src/main/res/navigation/nav_graph.xml

Fixes https://mifosforge.jira.com/browse/MOBILE-108

Fixes #2000 : Navigation component implementation : GroupDetails

---

build.gradle
mifosng-android/build.gradle
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerCenter.kt
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerClient.kt
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerGroups.kt
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerOffices.kt
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerStaff.kt
mifosng-android/src/main/java/com/mifos/mappers/centers/CenterMapper.kt
mifosng-android/src/main/java/com/mifos/mappers/centers/GetCentersResponseMapper.kt
mifosng-android/src/main/java/com/mifos/mappers/clients/ClientMapper.kt
mifosng-android/src/main/java/com/mifos/mappers/clients/GetClientResponseMapper.kt
mifosng-android/src/main/java/com/mifos/mappers/groups/GetGroupsResponseMapper.kt
mifosng-android/src/main/java/com/mifos/mappers/groups/GroupMapper.kt
mifosng-android/src/main/java/com/mifos/mappers/offices/GetOfficeResponseMapper.kt
mifosng-android/src/main/java/com/mifos/mappers/staffs/StaffMapper.kt
mifosng-android/src/main/java/com/mifos/repositories/CreateNewClientRepository.kt
mifosng-android/src/main/java/com/mifos/repositories/CreateNewClientRepositoryImp.kt
mifosng-android/src/main/java/com/mifos/ui/activities/LoginActivity.kt
mifosng-android/src/main/java/com/mifos/viewmodels/LoginViewModel.kt
mifosng-android/src/test/java/com/mifos/viewmodels/ClientChargeViewModelTest.kt
mifosng-android/src/test/java/com/mifos/viewmodels/LoanChargeViewModelTest.kt
mifosng-android/src/test/java/com/mifos/viewmodels/LoginViewModelTest.kt
mifosng-android/src/test/java/com/mifos/viewmodels/SearchViewModelTest.kt

Fixes https://mifosforge.jira.com/browse/MOBILE-137  https://mifosforge.jira.com/browse/MOBILE-138 https://mifosforge.jira.com/browse/MOBILE-139 https://mifosforge.jira.com/browse/MOBILE-44 https://mifosforge.jira.com/browse/MOBILE-140 https://mifosforge.jira.com/browse/MOBILE-141 https://mifosforge.jira.com/browse/MOBILE-142

Fixes #2035 : Fineract SDK Implementation : client, center, group list

---

mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerCenter.kt
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerClient.kt
mifosng-android/src/main/java/com/mifos/api/datamanager/DataManagerDataTable.kt
mifosng-android/src/main/java/com/mifos/mappers/clients/GetClientsClientIdAccountMapper.kt
mifosng-android/src/main/java/com/mifos/mappers/clients/GetIdentifiersTemplateMapper.kt
mifosng-android/src/main/java/com/mifos/mappers/clients/IdentifierMapper.kt
mifosng-android/src/main/java/com/mifos/mappers/dataTable/GetDataTablesResponseMapper.kt
mifosng-android/src/main/java/com/mifos/repositories/ActivateRepository.kt
mifosng-android/src/main/java/com/mifos/repositories/ActivateRepositoryImp.kt
mifosng-android/src/main/java/com/mifos/repositories/ClientIdentifiersRepository.kt
mifosng-android/src/main/java/com/mifos/repositories/ClientIdentifiersRepositoryImp.kt
mifosng-android/src/main/java/com/mifos/repositories/DataTableDataRepository.kt
mifosng-android/src/main/java/com/mifos/repositories/DataTableDataRepositoryImp.kt
mifosng-android/src/main/java/com/mifos/viewmodels/ActivateViewModel.kt
mifosng-android/src/main/java/com/mifos/viewmodels/ClientIdentifiersViewModel.kt
mifosng-android/src/main/java/com/mifos/viewmodels/DataTableDataViewModel.kt

Fixes https://mifosforge.jira.com/browse/MOBILE-143 , https://mifosforge.jira.com/browse/MOBILE-144,  https://mifosforge.jira.com/browse/MOBILE-146

Fixes #2035 : Fineract SDK Implementation : Client, Center,DataTable services

---

renovate.json

Fixes #2043 : Discontinuing Renobot for Dependency Upgrades

---

README.md

design : README.md update

---

README.md

docs: update slack link

---

mifosng-android/src/main/java/com/mifos/api/BaseUrl.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/activity/splashscreen/SplashScreenActivity.kt

fix: endpoint dev to demo and switch instance domain to app local

---

README.md

docs: added demo credentials

---

mifosng-android/src/main/AndroidManifest.xml

Fixes #1643 empty screen fixed in individual collection sheet

---

README.md

docs: notice in README.md

---

secrets.defaults.properties

fix: endpoint dev is not working

---

core/common/build.gradle.kts
core/common/src/main/java/com/mifos/core/common/utils/BaseUrl.kt
core/common/src/main/java/com/mifos/core/common/utils/JsonExtension.kt
core/model/build.gradle.kts
core/model/src/main/kotlin/com/mifos/core/model/ServerConfig.kt
core/network/src/main/java/com/mifos/core/network/BaseUrl.kt
secrets.defaults.properties

Jira: https://mifosforge.jira.com/browse/MIFOSAC-166

Convert server config string into json string

---

core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosEditTextField.kt

Fixed Build Error

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatable/DataTableFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatable/DataTableScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatable/DataTableUiState.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatable/DataTableViewModel.kt

jira: https://mifosforge.jira.com/browse/MIFOSAC-194
xml (before) | compose (now)
-------|------

refactor: Migrate DataTable Fragment to compose

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loantransactions/LoanTransactionsFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loantransactions/LoanTransactionsFragmentOld.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loantransactions/LoanTransactionsScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loantransactions/LoanTransactionsViewModel.kt
mifosng-android/src/main/res/values/strings.xml

https://mifosforge.jira.com/browse/MIFOSAC-199
[Screencast_07_05_2024_08:33:24_AM.webm](https://github.com/openMF/android-client/assets/78101731/87349777-ac84-45b5-9015-eebbf6a9454d)
-------------|-----------------------

refactor: Migrate loan transactions fragment to compose

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanrepaymentschedule/LoanRepaymentScheduleFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanrepaymentschedule/LoanRepaymentScheduleFragmentOld.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanrepaymentschedule/LoanRepaymentScheduleScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanrepaymentschedule/LoanRepaymentScheduleViewModel.kt

Fixes [JIRA](https://mifosforge.jira.com/browse/MIFOSAC-197)
XML (before) | compose(after)
-------|-------

refactor: migrate loan repayment schedule fragment to compose

---

core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosEditTextField.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupFragmentOld.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupViewModel.kt
mifosng-android/src/main/res/layout/fragment_create_new_group.xml
mifosng-android/src/main/res/values/strings.xml

JIRA: https://mifosforge.jira.com/browse/MIFOSAC-174
XML (before) | compose (after)
----------|-------
[Screencast_07_01_2024_12:55:06_AM.webm](https://github.com/openMF/android-client/assets/78101731/4a2e1475-de03-4430-bd2d-b19d72627aa3)

refactor: Migrate CreateNewGroup Fragment to compose

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountapproval/LoanAccountApproval.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountapproval/LoanAccountApprovalFragmentOld.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountapproval/LoanAccountApprovalScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountapproval/LoanAccountApprovalUiState.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountapproval/LoanAccountApprovalViewModel.kt
mifosng-android/src/main/res/values/strings.xml

Jira: https://mifosforge.jira.com/browse/MIFOSAC-211
------------|-----------|

refactor: Migrate loan account approval fragment to compose

---

core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosEditTextField.kt
feature/auth/src/main/java/com/mifos/feature/auth/login/presentation/LoginScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/createnewgroup/CreateNewGroupScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountdisbursement/LoanAccountDisbursementFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountdisbursement/LoanAccountDisbursementFragmentOld.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountdisbursement/LoanAccountDisbursementScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountdisbursement/LoanAccountDisbursementViewModel.kt
mifosng-android/src/main/res/values/strings.xml

Jira - https://mifosforge.jira.com/browse/MIFOSAC-210
XML (before) | compose(now)
-------------------|--------------------|

refactor: Migrate LoanAmountDisbursement fragment to compose

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveylist/SurveyListFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveylist/SurveyListFragmentOld.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveylist/SurveyListScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveylist/SurveyListViewModel.kt
mifosng-android/src/main/res/layout/fragment_survey_list.xml

JIRA - https://mifosforge.jira.com/browse/MIFOSAC-190
-------|-------

refactor: Migrate surveyList fragment to compose

---

core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosSweetError.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccountapproval/LoanAccountApprovalScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccountapproval/SavingsAccountApprovalFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccountapproval/SavingsAccountApprovalFragmentOld.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccountapproval/SavingsAccountApprovalScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccountapproval/SavingsAccountApprovalUiState.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/savingsaccountapproval/SavingsAccountApprovalViewModel.kt
mifosng-android/src/main/res/values/strings.xml

[MIFOSAC-215](https://mifosforge.jira.com/browse/MIFOSAC-215)
xml (before) |  compose (after)
------------------|--------------------------|
[MIFOSAC-215]: https://mifosforge.jira.com/browse/MIFOSAC-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: Migrate savings account approval fragment to compose

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncsavingsaccounttransaction/SyncSavingsAccountTransactionFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncsavingsaccounttransaction/SyncSavingsAccountTransactionScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncsavingsaccounttransaction/SyncSavingsAccountTransactionUiState.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncsavingsaccounttransaction/SyncSavingsAccountTransactionViewModel.kt

Fixes #[237](https://mifosforge.jira.com/browse/MIFOSAC-237)
Before:
After:

Refactor:Migrate SyncSavingsAccountTransactionFragment to Compose

---

core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosEmptyContent.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncgrouppayloads/SyncGroupPayloadsFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncgrouppayloads/SyncGroupPayloadsScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncgrouppayloads/SyncGroupPayloadsUiState.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/offline/syncgrouppayloads/SyncGroupPayloadsViewModel.kt
mifosng-android/src/main/res/values/strings.xml

Jira Task: [MIFOSAC-235](https://mifosforge.jira.com/browse/MIFOSAC-235)
Compose UI: 
[MIFOSAC-235]: https://mifosforge.jira.com/browse/MIFOSAC-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: sync group payload migration

---

core/designsystem/src/main/java/com/mifos/core/designsystem/icon/MifosIcon.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncgroupsdialog/SyncGroupDialogScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncgroupsdialog/SyncGroupsDialogFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncgroupsdialog/SyncGroupsDialogUiState.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncgroupsdialog/SyncGroupsDialogViewModel.kt
mifosng-android/src/main/res/layout/fragment_survey_question.xml

Jira Task: [MIFOSAC-228](https://mifosforge.jira.com/browse/MIFOSAC-228)
[MIFOSAC-228]: https://mifosforge.jira.com/browse/MIFOSAC-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: sync group dialog migration

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveyquestion/SurveyQuestionActivity.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveyquestion/SurveyQuestionFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveyquestion/SurveyQuestionScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveyquestion/SurveyQuestionsComposeActivity.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveysubmit/SurveySubmitFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveysubmit/SurveySubmitScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveysubmit/SurveySubmitUiState.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/surveysubmit/SurveySubmitViewModel.kt

Fixes #2169 
Fixes #2168
Jira Task : [link](https://mifosforge.jira.com/browse/MIFOSAC-213)
Jira Task : [link](https://mifosforge.jira.com/browse/MIFOSAC-214)
<table style="border: 1px solid black;">
<tr>
<td  style="border: 1px solid black ;">
</td>
<td  style="border: 1px solid black ;">
</td>
<td  style="border: 1px solid black ;">
</td>
</table>
https://github.com/user-attachments/assets/203cafbf-969c-4a96-9279-7fb6dc47e693

refactor: Survey Question and Survey Submit Screen in Compose

---

mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/synccenterdialog/SyncCentersDialogFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/synccenterdialog/SyncCentersDialogScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/synccenterdialog/SyncCentersDialogUiState.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/synccenterdialog/SyncCentersDialogViewModel.kt

Fixes #[Issue_Number](https://mifosforge.jira.com/browse/MIFOSAC-225)
Before:
After:

Refactor:Migrate Sync Centers Dialog Fragment to compose

---

core/data/src/main/java/com/mifos/core/data/repository/SyncGroupsDialogRepository.kt
core/data/src/main/java/com/mifos/core/data/repository_imp/SyncGroupsDialogRepositoryImp.kt
feature/groups/src/main/java/com/mifos/feature/groups/sync_group_dialog/SyncGroupDialogScreen.kt
feature/groups/src/main/java/com/mifos/feature/groups/sync_group_dialog/SyncGroupsDialogUiState.kt
feature/groups/src/main/java/com/mifos/feature/groups/sync_group_dialog/SyncGroupsDialogViewModel.kt
feature/groups/src/main/res/values/strings.xml
mifosng-android/src/main/java/com/mifos/mifosxdroid/dialogfragments/syncgroupsdialog/SyncGroupsDialogFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/injection/module/RepositoryModule.kt

fix: move syncGroupDialog to module

---

feature/note/src/main/java/com/mifos/feature/note/NoteScreen.kt
feature/note/src/main/java/com/mifos/feature/note/NoteViewModel.kt
feature/note/src/main/java/com/mifos/feature/note/navigation/NoteNavigation.kt
feature/note/src/main/java/com/mifos/feature/note/navigation/NoteScreens.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/components/Navigation.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/note/NoteFragment.kt

[JIRA](https://mifosforge.jira.com/browse/MIFOSAC-257)

feat: implemented compose navigation in note module

---

feature/about/src/main/java/com/mifos/feature/about/navigation/AboutScreens.kt
feature/about/src/main/java/com/mifos/feature/about/navigation/AccountNavigation.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/HomeDestinationsScreen.kt

Fixes [JIRA](https://mifosforge.jira.com/browse/MIFOSAC-258)

feat: Implemented compose navigation in about module

---

feature/settings/src/main/java/com/mifos/feature/settings/navigation/SettingsNavigation.kt
feature/settings/src/main/java/com/mifos/feature/settings/navigation/SettingsScreens.kt
feature/settings/src/main/java/com/mifos/feature/settings/settings/SettingsScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/HomeDestinationsScreen.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/activity/setting/SettingsFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/activity/setting/UpdateServerConfigFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/components/Navigation.kt

Fixes [JIRA](https://mifosforge.jira.com/browse/MIFOSAC-269)

feat: Implemented compose navigation in settings module

---

feature/client/src/main/java/com/mifos/feature/client/navigation/ClientNavigation.kt
feature/data-table/src/main/java/com/mifos/feature/data_table/dataTableList/DataTableListScreen.kt
feature/data-table/src/main/java/com/mifos/feature/data_table/dataTableList/DataTableListViewModel.kt
feature/data-table/src/main/java/com/mifos/feature/data_table/navigation/DataTableNavigation.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/components/Navigation.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/clientlist/ClientListFragment.kt
mifosng-android/src/main/java/com/mifos/mifosxdroid/online/datatablelistfragment/DataTableListFragment.kt

fix: Implemented leftout nav-routes in compose navigation

---

core/data/src/main/java/com/mifos/core/data/repository_imp/SavingsAccountRepositoryImp.kt

App crash issue Resolved

---

feature/note/build.gradle.kts
feature/note/src/androidTest/java/com/mifos/feature/note/ExampleInstrumentedTest.kt
feature/note/src/main/AndroidManifest.xml
feature/note/src/main/java/com/mifos/feature/note/NoteScreen.kt
feature/note/src/main/java/com/mifos/feature/note/NoteUiState.kt
feature/note/src/main/java/com/mifos/feature/note/NoteViewModel.kt
feature/note/src/main/java/com/mifos/feature/note/navigation/NoteNavigation.kt
feature/note/src/main/java/com/mifos/feature/note/navigation/NoteScreens.kt
feature/note/src/main/res/values/res.xml
feature/note/src/test/java/com/mifos/feature/note/ExampleUnitTest.kt

Fixes [JIRA](https://mifosforge.jira.com/jira/software/c/projects/MOBILE/boards/57?label=mobile%2Candroid-client&selectedIssue=MIFOSAC-279)
Applying spotless and detekt on feature/note module

applying spotless and detekt to note module (JIRA 279)

---

core/datastore/build.gradle.kts
core/datastore/src/main/AndroidManifest.xml
core/datastore/src/main/java/com/mifos/core/datastore/PrefManager.kt
core/datastore/src/test/java/com/mifos/core/database/ExampleUnitTest.kt

Fixes [JIRA](https://mifosforge.jira.com/browse/MIFOSAC-302)

refactor: applied spotless and detekt on core:datastore

---

core/common/build.gradle.kts
core/common/src/main/AndroidManifest.xml
core/common/src/main/java/com/mifos/core/common/enums/MifosAppLanguage.kt
core/common/src/main/java/com/mifos/core/common/model/user/Role.kt
core/common/src/main/java/com/mifos/core/common/model/user/User.kt
core/common/src/main/java/com/mifos/core/common/network/MifosDispatchers.kt
core/common/src/main/java/com/mifos/core/common/network/di/CoroutineScopesModule.kt
core/common/src/main/java/com/mifos/core/common/network/di/DispatchersModule.kt
core/common/src/main/java/com/mifos/core/common/utils/AndroidVersionUtil.kt
core/common/src/main/java/com/mifos/core/common/utils/BaseUrl.kt
core/common/src/main/java/com/mifos/core/common/utils/Constants.kt
core/common/src/main/java/com/mifos/core/common/utils/DateHelper.kt
core/common/src/main/java/com/mifos/core/common/utils/FileUtils.kt
core/common/src/main/java/com/mifos/core/common/utils/JsonExtension.kt
core/common/src/main/java/com/mifos/core/common/utils/LanguageHelper.kt
core/common/src/main/java/com/mifos/core/common/utils/MapDeserializer.kt
core/common/src/main/java/com/mifos/core/common/utils/Network.kt
core/common/src/main/java/com/mifos/core/common/utils/NetworkUtilsWrapper.kt
core/common/src/main/java/com/mifos/core/common/utils/Page.kt
core/common/src/main/java/com/mifos/core/common/utils/Resource.kt
core/common/src/main/java/com/mifos/core/common/utils/Utils.kt
core/common/src/main/res/values/strings.xml
core/common/src/test/java/com/mifos/core/common/ExampleUnitTest.kt

Fixes https://mifosforge.jira.com/browse/MIFOSAC-293 

MIFOSAC-293 Applied Spotless And Detekt in Core: Common

---

core/ui/build.gradle.kts
core/ui/src/androidTest/java/com/mifos/core/ui/ExampleInstrumentedTest.kt
core/ui/src/main/AndroidManifest.xml
core/ui/src/main/java/com/mifos/core/ui/components/MifosEmptyUi.kt
core/ui/src/main/java/com/mifos/core/ui/components/MifosFAB.kt
core/ui/src/main/java/com/mifos/core/ui/components/MifosToolbar.kt
core/ui/src/main/java/com/mifos/core/ui/components/MultiFloatingActionButton.kt
core/ui/src/main/java/com/mifos/core/ui/util/DevicePreviews.kt
core/ui/src/main/java/com/mifos/core/ui/util/GroupListPreviewParameterProvider.kt
core/ui/src/main/java/com/mifos/core/ui/util/SearchResultPreviewParameter.kt
core/ui/src/main/res/drawable/core_ui_ic_centers_24dp.xml
core/ui/src/main/res/drawable/core_ui_ic_group_black_24dp.xml
core/ui/src/main/res/drawable/core_ui_ic_person_black_24dp.xml
core/ui/src/main/res/values/core_ui_strings.xml
core/ui/src/test/java/com/mifos/core/ui/ExampleUnitTest.kt

Fixes [JIRA](https://mifosforge.jira.com/browse/MIFOSAC-301)

refactor: applied spotless and detekt on core:ui

---

feature/center/src/main/java/com/mifos/feature/center/centerDetails/CenterDetailsScreen.kt
feature/center/src/main/java/com/mifos/feature/center/centerGroupList/GroupListScreen.kt
feature/center/src/main/java/com/mifos/feature/center/centerList/ui/CenterListScreen.kt
feature/center/src/main/java/com/mifos/feature/center/createCenter/CreateNewCenterScreen.kt
feature/center/src/main/java/com/mifos/feature/center/syncCentersDialog/SyncCentersDialogScreen.kt
feature/center/src/main/java/com/mifos/feature/center/syncCentersDialog/SyncCentersDialogViewModel.kt

MIFOSAC-303
Fixes [Jira](https://mifosforge.jira.com/browse/MIFOSAC-303)
https://github.com/user-attachments/assets/e0d34842-a613-425a-9dc9-a68bdaf59c33

Refactor: Apply spotless and detekt on Center module

---

config/detekt/detekt.yml
core/designsystem/build.gradle.kts
core/designsystem/src/main/AndroidManifest.xml
core/designsystem/src/main/java/com/mifos/core/designsystem/component/DrawingState.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosAlertDailog.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosAndroidClientIcon.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosBottomSheet.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosDrawingCanvas.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosEditTextField.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosEmptyContent.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosMenuDropdown.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosPermissionBox.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosProgressIndicator.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosScaffold.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosSweetError.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosTabRow.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/component/MifosTextFieldDropdown.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/icon/MifosIcons.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/theme/Color.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/theme/MifosTextStyle.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/theme/Theme.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/utility/PathState.kt
core/designsystem/src/main/java/com/mifos/core/designsystem/utility/TabContent.kt
core/designsystem/src/main/res/drawable/core_designsystem_ic_error_black_24dp.xml
core/designsystem/src/main/res/values/strings.xml
core/designsystem/src/test/java/com/mifos/core/designsystem/ExampleUnitTest.kt

Applied Spotless and Detekt to the "feature-coreDesignSystem" module.
https://mifosforge.jira.com/browse/MIFOSAC-297

Applied Spotless and Detekt to the "coreDesignSystem" module

---

mifosng-android/google-services.json

Fixes - [Jira-#Issue_Number](https://mifosforge.jira.com/browse/MIFOSAC-)
Didn't create a Jira ticket, click [here](https://mifosforge.jira.com/jira/software/c/projects/MIFOSAC/issues/) to create new.
| Before                                     | After                                  |
|--------------------------------------------|----------------------------------------|
|                                            |                                        |

chore: Upload `google-services.json` file

---

fastlane/FastFile
fastlane/metadata/android/en-US/changelogs/default.txt
mifosng-android/build.gradle.kts

Fixes - [Jira-#Issue_Number](https://mifosforge.jira.com/browse/MIFOSAC-)
Didn't create a Jira ticket, click [here](https://mifosforge.jira.com/jira/software/c/projects/MIFOSAC/issues/) to create new.
| Before                                     | After                                  |
|--------------------------------------------|----------------------------------------|
|                                            |                                        |

fix: Play Store Release CI/CD

---

core/domain/src/main/java/com/mifos/core/domain/useCases/GetSavingsAccountTransactionUseCase.kt

Fixes [JIRA](https://mifosforge.jira.com/jira/software/c/projects/MIFOSAC/issues/MIFOSAC-312?filter=allissues&jql=project%20%3D%20%22MIFOSAC%22%20ORDER%20BY%20created%20DESC)
https://github.com/user-attachments/assets/d425056e-2f39-436e-b80c-f012af858891

savings account summary - non-null parameter is null(Solved)
